Implemented Pasta curves
Zondax/ledger-zcash pull request #7
Opened 2020-12-28 01:26 UTC by jspada

2021-01-02 20:24 UTC, jleni commented
Could you justify this PR? Why is this necessary in this app?

2021-01-03 23:42 UTC, jspada commented
This is needed for the Ledger app to generate keypairs on Pollard and Halo2.  It is an implementation of the new Pasta curves (https://github.com/zcash/pasta) and corresponding ECC code for deriving the new Pollar/Halo2 public keys from the secret.  Because Pasta is not supported by Ledger in hardware, we must implement it using Ledger's low-level modular arithmetic API.  This and the elliptic curve scalar multiplication, in particular, must be done by the app, since the secret key is only available on the Ledger device.

Pollard is intended to be ready for deployment in mid-2021.

2021-01-04 22:53 UTC, jleni commented
Thanks Joseph. Very nice work!

My question was more focused on why we need this addition to master this point in time. 
At the moment, we consider this app to be Sapling compatible. We will soon make public milestone 3, that is under review.
For this reason and to avoid further delays, we would prefer to keep this PR in a branch.

With respect to curves, we did manage to use Rust-based code for JubJub. As we approach to Pollard, we may revisit this topic, though, it is very likely due to the complexity of Pasta, that we will manage to use Rust again. Nevertheless, this is a great help in that direction and we are looking forward to seeing Pasta and Pollard being adopted soon!

2021-01-05 00:16 UTC, jspada commented
Thanks!

Yeah, it would definitely better on a "pasta" branch.  If you create the branch, then I'll update the pull request!

Regarding Rust- this is our preference also.  Our plan is to iterate on a working solution and this pull request is the first version that works.  The next iteration will convert this to Rust before making a number of ECC improvements for side-channel resistance.

2021-01-06 13:23 UTC, jleni requested changes
We will integrate in the next release as we approach to Pollard

2021-01-07 10:38 UTC, merged

2021-01-07 10:38 UTC, jleni commented
Thanks again @jspada . Awesome contribution!

2021-01-07 14:02 UTC, jspada commented
Perfect- thank you!  I'll move on to converting to Rust and side-channel resistance next.

2021-01-11 21:44 UTC, jspada commented
Hi @jleni - wanted to discuss with you about putting in some unit tests.  Is there somewhere we can chat? Are you on discord?